"""Plan enforcement: language limits, rate limiting, expiry, and usage tracking.

The tokens file is generated by our licensing infrastructure, so the entitlements in it
are the customer's license terms. These tests pin the contract that the processor,
not the client, enforces them.
"""

import asyncio
import datetime
import json
import uuid
from pathlib import Path

import httpx
import numpy as np
import yaml

from voicesniffer_processor.app import create_app
from voicesniffer_processor.models import TranscriptionResult
from voicesniffer_processor.opus import OpusPacketInfo
from voicesniffer_processor.rules import RulePack
from voicesniffer_processor.settings import ProcessorSettings


def test_extended_token_entries_parse_with_entitlements(tmp_path: Path) -> None:
    settings = make_settings(
        tmp_path,
        {
            "starter-server": {
                "token": "starter-token",
                "plan": "starter",
                "languages": ["en"],
                "rate-limit-per-minute": 60,
                "expires": "2030-01-01T00:00:00+00:00",
            },
            "legacy-server": "legacy-token",
        },
    )

    starter = settings.credential_for_token("starter-token")
    assert starter is not None
    assert starter.server_id == "starter-server"
    assert starter.plan == "starter"
    assert starter.languages == frozenset({"en"})
    assert starter.rate_limit_per_minute == 60
    assert starter.expires_at is not None and starter.expires_at.year == 2030

    legacy = settings.credential_for_token("legacy-token")
    assert legacy is not None
    assert legacy.plan == "selfhost"
    assert legacy.languages is None
    assert legacy.rate_limit_per_minute is None
    assert legacy.expires_at is None


def test_pinned_language_outside_plan_is_refused(tmp_path: Path) -> None:
    app = build_app(tmp_path, languages=["en"])

    response = post(app, headers(request_language="cs"), b"\x00\x01a")

    assert response.status_code == 403
    assert response.json()["code"] == "language_not_licensed"


def test_auto_detect_only_evaluates_licensed_packs(tmp_path: Path) -> None:
    # The transcriber detects Czech and the Czech pack would match, but the plan
    # only licenses English, so the verdict must stay clean.
    restricted = build_app(
        tmp_path,
        languages=["en"],
        detected_language="cs",
        transcription_text="zakazana fraze",
    )
    unrestricted = build_app(
        tmp_path,
        languages=None,
        detected_language="cs",
        transcription_text="zakazana fraze",
    )

    limited = post(restricted, headers(request_language="auto"), b"\x00\x01a")
    full = post(unrestricted, headers(request_language="auto"), b"\x00\x01a")

    assert limited.status_code == 200
    assert limited.json()["severity"] == 0
    assert limited.json()["matches"] == []
    assert full.status_code == 200
    assert full.json()["severity"] == 2


def test_rate_limit_returns_429_with_retry_after(tmp_path: Path) -> None:
    now = [1000.0]
    app = build_app(tmp_path, languages=["en"], rate_limit=2, clock=lambda: now[0])

    first = post(app, headers(), b"\x00\x01a")
    second = post(app, headers(), b"\x00\x01a")
    third = post(app, headers(), b"\x00\x01a")
    now[0] += 61.0
    fourth = post(app, headers(), b"\x00\x01a")

    assert (first.status_code, second.status_code) == (200, 200)
    assert third.status_code == 429
    assert third.json()["code"] == "rate_limited"
    assert int(third.headers["Retry-After"]) >= 1
    assert fourth.status_code == 200


def test_expired_license_gets_a_clear_error(tmp_path: Path) -> None:
    expired = (datetime.datetime.now(tz=datetime.UTC) - datetime.timedelta(days=1)).isoformat(
        timespec="seconds"
    )
    app = build_app(tmp_path, languages=["en"], expires=expired)

    response = post(app, headers(), b"\x00\x01a")

    assert response.status_code == 403
    assert response.json()["code"] == "license_expired"


def test_usage_endpoint_requires_auth_and_reports_counts(tmp_path: Path) -> None:
    app = build_app(tmp_path, languages=["en"], plan="starter")

    assert post(app, headers(), b"\x00\x01a").status_code == 200
    assert post(app, headers(request_language="cs"), b"\x00\x01a").status_code == 403

    unauthenticated = get(app, "/v1/usage", token=None)
    assert unauthenticated.status_code == 401

    report = get(app, "/v1/usage", token="secret-token")
    assert report.status_code == 200
    payload = report.json()
    assert payload["server_id"] == "server-a"
    assert payload["plan"] == "starter"
    assert payload["languages"] == ["en"]
    assert payload["moderated_languages"] == ["en"]
    assert payload["usage"]["requests"] == 2
    assert payload["usage"]["outcomes"]["success"] == 1
    assert payload["usage"]["outcomes"]["language_not_licensed"] == 1
    assert payload["usage"]["flagged"] == 1  # the successful request matched severity 2


def test_a_licence_for_a_language_with_no_rules_is_refused_rather_than_moderated_by_nothing(
    tmp_path: Path,
) -> None:
    """The same hole reached through the licence rather than the header.

    A credential entitled only to a language no pack covers narrows the entitled
    set to nothing, and `auto` over an empty set matched nothing while answering
    200. That is a customer paying for moderation and receiving silence, which
    is worse than an error, because an error is something an operator can see.
    """
    app = build_app(tmp_path, languages=["fi"])

    pinned = post(app, headers(request_language="fi"), b"\x00\x01a")
    assert pinned.status_code == 400
    assert pinned.json()["code"] == "language_unsupported"

    detected = post(app, headers(request_language="auto"), b"\x00\x01a")
    assert detected.status_code == 400
    assert detected.json()["code"] == "language_unsupported"


def test_usage_reports_which_licensed_languages_actually_have_rules(tmp_path: Path) -> None:
    # `languages` is what the licence sold; `moderated_languages` is what this
    # node can act on. An operator has no other way to notice the difference.
    app = build_app(tmp_path, languages=["en", "fi"])

    payload = get(app, "/v1/usage", token="secret-token").json()

    assert payload["languages"] == ["en", "fi"]
    assert payload["moderated_languages"] == ["en"]


def test_usage_reports_every_installed_pack_for_an_unrestricted_licence(tmp_path: Path) -> None:
    app = build_app(tmp_path, languages=None)

    payload = get(app, "/v1/usage", token="secret-token").json()

    assert payload["languages"] == "all"
    assert payload["moderated_languages"] == ["cs", "en"]


# ---------------------------------------------------------------- helpers


def make_settings(tmp_path: Path, entries: dict) -> ProcessorSettings:
    token_file = tmp_path / "tokens.json"
    token_file.write_text(json.dumps(entries), encoding="utf-8")
    return ProcessorSettings.from_environment({"VOICESNIFFER_TOKENS_FILE": str(token_file)})


def build_app(
    tmp_path: Path,
    *,
    languages: list[str] | None,
    plan: str = "starter",
    rate_limit: int | None = None,
    expires: str | None = None,
    detected_language: str = "en",
    transcription_text: str = "blocked phrase",
    clock=None,
):
    entry: dict = {"token": "secret-token", "plan": plan}
    if languages is not None:
        entry["languages"] = languages
    if rate_limit is not None:
        entry["rate-limit-per-minute"] = rate_limit
    if expires is not None:
        entry["expires"] = expires
    settings = make_settings(tmp_path, {"server-a": entry})

    def transcribe(_samples: np.ndarray, _language: str) -> TranscriptionResult:
        return TranscriptionResult(text=transcription_text, language=detected_language)

    extra = {} if clock is None else {"clock": clock}
    return create_app(
        settings,
        transcribe=transcribe,
        rule_packs={
            "en": rule_pack(tmp_path, "en", "blocked phrase"),
            "cs": rule_pack(tmp_path, "cs", "zakazana fraze"),
        },
        inspect_packet=lambda _packet: OpusPacketInfo(samples_48k=960, channels=1),
        decode_audio=lambda _envelope: np.ones(320, dtype=np.float32),
        **extra,
    )


def rule_pack(tmp_path: Path, language: str, term: str) -> RulePack:
    rule_file = tmp_path / f"{language}.yml"
    rule_file.write_text(
        yaml.safe_dump(
            {
                "version": 1,
                "language": language,
                "rules": [
                    {
                        "id": f"{language}.test.blocked",
                        "term": term,
                        "category": "harassment",
                        "severity": 2,
                        "match": "exact",
                        "variants": [],
                        "context_required": False,
                    }
                ],
            },
            sort_keys=False,
        ),
        encoding="utf-8",
    )
    return RulePack.load(rule_file)


def headers(request_language: str = "en") -> dict[str, str]:
    return {
        "Authorization": "Bearer secret-token",
        "Content-Type": "application/vnd.voicesniffer.opus.v1",
        "Accept": "application/json",
        "X-Request-Id": str(uuid.uuid4()),
        "X-VoiceSniffer-Player-Id": str(uuid.uuid4()),
        "X-VoiceSniffer-Language": request_language,
        "X-VoiceSniffer-Preroll-Samples": "0",
    }


def post(app, request_headers: dict[str, str], body: bytes) -> httpx.Response:
    async def request() -> httpx.Response:
        transport = httpx.ASGITransport(app=app)
        async with httpx.AsyncClient(transport=transport, base_url="http://processor") as client:
            return await client.post("/v1/moderate", headers=request_headers, content=body)

    return asyncio.run(request())


def get(app, path: str, *, token: str | None) -> httpx.Response:
    request_headers = {} if token is None else {"Authorization": f"Bearer {token}"}

    async def request() -> httpx.Response:
        transport = httpx.ASGITransport(app=app)
        async with httpx.AsyncClient(transport=transport, base_url="http://processor") as client:
            return await client.get(path, headers=request_headers)

    return asyncio.run(request())
