"""What the shipped packs must *cover*, as opposed to how the matcher behaves.

``test_rules_regression.py`` pins the mechanism: that a swapped consonant is
refused, that a held-down letter is still caught, that every listed term still
fires. It is deliberately vocabulary-free -- it reads the packs at run time and
asserts properties of the predicate.

This file is the other half, and every corpus in it is a list of inputs that
were **confirmed to fire against a shipped pack** -- not inputs somebody thought
might be risky. The first version of this file was written the other way round
and passed while the packs hour-muted ``nagas`` (a Twilight Forest boss),
``nagar``, ``nagger``, ``ritard``, ``retards`` as an ordinary verb, ``bezny``
(``běžný`` de-accented), ``cukání``, ``cákání``, ``Cogan``, ``rákosníka`` (a reed
warbler), ``I'll stab you with my sword``, ``I'll shoot you with my bow``,
``I'm going to shoot up at the ghast``, ``kill yourself to respawn``, ``are you
naked or wearing armour`` and ``I've got your IP for the server``. It passed
because the corpus used ``shoot the skeleton`` instead of ``I'll shoot you with
my bow``, and ``I am naked`` instead of ``are you naked``. Every one of those is
now below.

A benign corpus alone cannot prove much: it also passes if ``_match_fuzzy``
returns ``None`` for everything. ``test_fuzzy_matching_is_alive`` is the control.

The token-level instrument is ``processor/bench/domain-corpus/fp_surface.py``,
which walks a word list through the real matcher. It needs a system dictionary,
so it runs on Linux rather than in CI. It is a required gate before a fuzzy
pattern changes -- but it is **not** sufficient, and it is worth knowing why
before trusting it. Run against the pre-fix patterns on 2026-07-29 it found
``fagot``/``fagots`` in both English dictionaries and ``cogan``/``cygan``/
``cákaný`` in ``cs_CZ.dic`` -- and it did *not* find ``nagas``, ``nagar``,
``nagger`` or ``ritard``, because a Twilight Forest boss, a place name, a derived
form and a music abbreviation are in no word dictionary. Those needed a second
corpus, generated by ``minecraft_vocabulary.py`` from the vendored
``minecraft-data`` package, which finds all of them.

So: three layers, none of which subsumes another. The dictionary sweep covers
ordinary vocabulary, the domain sweep covers game vocabulary, and this file
covers phrases -- a sweep is token-level and can say nothing about ``are you
naked or wearing armour``.

One trap in the sweep itself, learned the hard way: ``fp_surface.py`` defaults to
``--min-length 4`` and silently skips shorter tokens. The transcriber variants
added on 2026-07-30 include the three-character ``nga``, so the default run
reported a clean gate while never looking at the one addition that warranted
looking at. Pass ``--min-length 3`` whenever a pack contains a phrase shorter
than four characters. Re-run at 3: 73,268 American, 72,718 British, 256,477
Czech and 5,419 Minecraft tokens, nothing fires.

Nothing here spells a slur: the must-flag side is threat, grooming and abuse
phrasing, and the hate rules are covered by the regression suite reading terms
out of the packs.
"""

import unicodedata
from pathlib import Path

import pytest

from voicesniffer_processor.rules import RulePack, _is_vowel

RULES_DIRECTORY = Path(__file__).resolve().parents[1] / "rules"

# Discovered, not listed. This was ``("en", "cs")``, which meant a pack added to
# the directory shipped without any of the checks below ever looking at it --
# the structural rules, the category coverage, and both benign corpora. The
# processor itself loads packs by globbing this directory
# (``__main__._load_rule_packs``), so the test set now matches what production
# actually runs.
LANGUAGES = tuple(sorted(path.stem for path in RULES_DIRECTORY.glob("*.yml")))
assert LANGUAGES, "no rule packs found; the pack directory moved"

# Confirmed severity-3 and severity-2 false positives from the review of the
# first version of these packs, in the sentence they were reproduced in. Each
# one fired before the fix; none may fire again.
CONFIRMED_ENGLISH_COLLISIONS = (
    "nagas are twilight forest bosses",
    "we visited nagar last year",
    "stop being a nagger",
    "the naggers in this chat are relentless",
    "play a ritard here",
    "heat retards curing",
    "the flame retardant blocks",
    "the ignition timing is retarded",
    "ill stab you with my sword",
    "i ll stab you with my sword",
    "ill shoot you with my bow",
    "im going to shoot up at the ghast",
    "shoot up at the ghast above us",
    "kill yourself to respawn at the bed",
    "kill yourself and respawn quickly",
    "are you naked or wearing armour",
    "ive got your ip for the server",
    "i have your ip so i can join",
    "ill find you and kill you in the nether",
    "join my discord for the raid",
    "there is a chink in the armour on the left",
    # `niga` and `nga` were added for the transcriber; the words they are one
    # edit from must stay clean, which is why both are exact and not fuzzy.
    "the naga boss hits really hard",
    "nagas are twilight forest bosses",
    "we visited nagar last year",
    "the bassoon is also called a fagot",
    "he plays the fagot in the orchestra",
)

CONFIRMED_CZECH_COLLISIONS = (
    "to je bezna vec",
    "to je bezny postup",
    "to je úplně běžný postup",
    "to cukani kamery oprav",
    "to cukání kamery oprav",
    "slysim cakani vody",
    "slyším cákání vody",
    "cogan se pripojil",
    "coogan se pripojil",
    "videl jsem rakosnika u rybnika",
    "viděl jsem rákosníka u rybníka",
    "rákosník obecný hnízdí v rákosí",
    "zastřelím tě lukem",
    "najdu tě a zabiju tě v netheru",
    "podřežu tě mečem",
    "najdu si tě na spawnu",
    "jsi nahý bez brnění",
    "jsi nahá bez brnění",
    "zabij se a respawni",
    "mám tvoji ip na ten server",
)

# Ordinary Minecraft speech, kept from the first version. These were never the
# problem -- they were too easy. Retained as a floor, not as the argument.
BENIGN_MINECRAFT = (
    "load the chunk before you build the farm",
    "this chunk is not loading properly again",
    "the chunk border is right under the water",
    "i will kill the ender dragon tonight",
    "kill the wither and grab the nether star",
    "just kill me so i respawn at the bed",
    "you killed me in pvp and that was rough",
    "shoot the skeleton with your bow already",
    "we got raided last night while we slept",
    "im coming to your base with all the tnt",
    "i know where your base is hidden",
    "i will find you and mine all your diamonds",
    "he is such a geek about redstone circuits",
    "spec the diamond gear before the raid",
    "send me the coordinates of the portal",
    "send me a screenshot of the build please",
    "add me on discord so we can voice chat",
    "are you home from school yet or not",
    "my mum is home so i have to log off",
    "take your armour off before you swim",
    "i am naked without my elytra on",
    "the villager trades here are really bad",
    "spawn camping is against the server rules",
    "put the creeper head on the fence post",
    "my base got griefed while i was offline",
)

BENIGN_MINECRAFT_CZECH = (
    "načti ten chunk než začneš stavět",
    "zabiju ender draka dneska večer",
    "zabij toho withera a vem si hvezdu",
    "zabij mě ať se respawnu u postele",
    "jdu si pro tebe do base s tnt",
    "vim kde mas base schovanou",
    "pošli mi souřadnice toho portálu",
    "pošli mi screenshot té stavby",
    "přidej si mě na discord ať můžeme mluvit",
    "jsi doma ze školy nebo ještě ne",
    "sundej si brnění než skočíš do vody",
    "ten villager má hrozný obchody",
    "někdo mi vygriefoval base",
)

# Threat-shaped gameplay. `zastřelím tě` and `najdu tě a zabiju` were severity 3
# and are now review tier, so they belong in the confirmed-collision corpus
# above; what stays here is speech that must reach no rule at all.
GAMEPLAY_THREATS_ENGLISH = (
    "i will kill you in pvp next round",
    "im gonna kill you when i get my gear",
    "ill kill you if you touch my chest",
    "im coming for you and your base",
    "youre dead when i find you",
    "im gonna destroy everything you built",
)

GAMEPLAY_THREATS_CZECH = (
    "zabiju tě až budu mít brnění",
    "jdu si pro tebe a tvoji base",
    "zničím ti všechno co jsi postavil",
)

# (utterance, exact expected verdict severity, rule that must be among the
# matches). Exact rather than ">=": a floor lets doxxing silently move from 2 to
# 3, and is satisfied by any unrelated severity-3 rule firing instead.
MUST_FLAG_ENGLISH = (
    ("i know where you live and im coming over", 3, "en.threat.violence"),
    ("I'll find your address bro", 3, "en.threat.violence"),
    ("ill find your address bro", 3, "en.threat.violence"),
    ("im going to shoot up the school tomorrow", 3, "en.threat.mass-violence"),
    ("i'm gonna rape you", 3, "en.threat.sexual-violence"),
    ("im gonna swat you tonight", 3, "en.threat.swatting"),
    ("im gonna dox you", 2, "en.threat.doxxing"),
    ("don't tell your parents about this okay", 3, "en.sexual.grooming"),
    ("dont tell your parents about this okay", 3, "en.sexual.grooming"),
    ("just send nudes already", 2, "en.sexual.explicit"),
    ("shut the fuck up already", 2, "en.harassment.abuse"),
    ("bro just go and drink bleach", 3, "en.harassment.self-harm"),
    ("kill yourself", 3, "en.harassment.self-harm"),
    ("youre a retard", 2, "en.hate.ableist-directed"),
    ("subscribe to my channel for more", 1, "en.spam.self-promo"),
    # Verbatim from a live built-in session, 2026-07-30. The speaker said the
    # slur three times; the transcriber wrote "Niga", "Nga" and "Niggar", and
    # only the last was caught. These are not obfuscations -- they are the model
    # spelling badly -- so no amount of matcher cleverness substitutes for having
    # them listed.
    ("Niga", 3, "en.hate.nword-listed"),
    ("Hello Nga", 3, "en.hate.nword-listed"),
    ("Niggar", 3, "en.hate.nword-listed"),
    ("K yourself", 3, "en.harassment.self-harm"),
)

MUST_FLAG_CZECH = (
    ("vím kde bydlíš", 3, "cs.threat.violence"),
    ("vim kde bydlis", 3, "cs.threat.violence"),
    ("neříkej to rodičům jasný", 3, "cs.sexual.grooming"),
    ("nerikej to rodicum jasny", 3, "cs.sexual.grooming"),
    ("pošli nudes", 2, "cs.sexual.explicit"),
    ("jdi do prdele ty zmrde", 2, "cs.harassment.abuse"),
    ("jdi se zabít ty hajzle", 3, "cs.harassment.self-harm"),
    ("zabij se", 3, "cs.harassment.self-harm"),
    # `střelba ve škole` was here and is now review tier: it is the bare topic
    # noun, and "viděl jsi tu střelbu ve škole ve zprávách" is a child talking
    # about the news. The phrasing that names the speaker still acts.
    ("zítra vystřílím školu", 3, "cs.threat.mass-violence"),
    ("ty cigáne", 3, "cs.hate.slur-directed"),
    ("zveřejním tvoji adresu", 2, "cs.threat.doxxing"),
    ("odebírej můj kanál", 1, "cs.spam.self-promo"),
    ("dej odber lidi", 1, "cs.spam.self-promo"),
)

# Patterns whose tier is a product decision rather than an implementation detail.
# Freezing rule ids alone was not enough: moving `fag` into a mute-tier rule left
# both ids in place and passed. These freeze the pattern.
MUST_BE_REVIEW_TIER = (
    # De-accented by the transcriber this is a Croatian and Slovene headword,
    # and an ordinary Portuguese word. It muted people for their own ethnonym.
    ("cs", "cigan"),
    ("en", "dyke"),
    ("en", "coon"),
    ("en", "fag"),
    ("en", "chink"),
    ("en", "gypsy"),
    ("en", "retard"),
    ("en", "retarded"),
    ("en", "are you naked"),
    ("en", "ive got your ip"),
    ("en", "ill stab you"),
    ("en", "ill shoot you"),
    ("en", "ill find you and kill you"),
    ("en", "join my discord"),
    ("en", "free diamonds"),
    ("en", "you suck"),
    ("en", "thats gay"),
    ("cs", "negr"),
    ("cs", "rákosník"),
    ("cs", "jsi nahý"),
    ("cs", "zastřelím tě"),
    ("cs", "mám tvoji ip"),
    ("cs", "kolik ti je let"),
    ("cs", "diamanty zdarma"),
    # The bare topic noun, in every pack that carried it at mute tier. `school
    # shooting` with nobody named is a news headline, and nineteen packs answered
    # it with an hour-long mute. Only fr.yml and de.yml were already correct,
    # which is why neither appears here: they have no bare form to hold down.
    ("bg", "стрелба в училището"),
    ("cs", "střelba ve škole"),
    ("da", "skoleskyderi"),
    ("el", "μακελειό στο σχολείο"),
    ("en", "school shooting"),
    ("es", "tiroteo en la escuela"),
    ("et", "koolitulistamine"),
    ("hr", "pucnjava u školi"),
    ("hu", "iskolai lövöldözés"),
    ("it", "sparatoria a scuola"),
    ("lt", "šaudymas mokykloje"),
    ("lv", "šaušana skolā"),
    ("nl", "schietpartij op school"),
    ("pl", "strzelanina w szkole"),
    ("pt", "tiroteio na escola"),
    ("ro", "împușcături la școală"),
    ("ru", "стрельба в школе"),
    ("sk", "streľba v škole"),
    ("sl", "streljanje v šoli"),
    ("sv", "skolskjutning"),
    ("uk", "стрілянина в школі"),
    # Wishing death in a game about dying. Every one of these was severity 3.
    ("en", "go and die"),
    ("en", "i hope you die"),
    ("cs", "chcípni"),
    ("da", "gå hen og dø"),
    ("el", "ψόφα ρε"),
    ("es", "ojalá te mueras"),
    ("hu", "dögölj meg"),
    ("lv", "nosprāgsti"),
    ("ru", "сдохни"),
    # Self-harm disclosure. Review tier is the product decision, not a hedge:
    # Minecraft has a literal reading of every one of these and the output that
    # helps is a moderator, never a mute.
    ("en", "i want to kill myself"),
    ("en", "i want to die"),
    ("en", "kms"),
    ("cs", "chci se zabít"),
    ("de", "ich will mich umbringen"),
    ("pl", "chcę się zabić"),
    ("pt", "quero morrer"),
    ("ru", "хочу умереть"),
    # Cross-language collisions: correct Slovene, correct Hungarian, and both of
    # them ordinary words to somebody else on the same server.
    ("sl", "pedra"),
    ("hu", "cigo"),
    # Found by sweeping every review-tier pattern through every other pack rather
    # than reported: correct Estonian, and the ordinary clinical word in Romanian,
    # where ro.yml already held it at review tier.
    ("et", "pederast"),
    # "I'll kill you" in German, which is PvP speech. It used to match *nothing*,
    # because the allow entry that stopped the self-harm rule misfiring on it
    # suppressed every other rule too.
    ("de", "ich bring dich um"),
)

# The other direction: a rule quietly demoted to review tier stops muting
# anybody, and nothing else in the suite would say so.
MUST_CARRY_AUTOMATIC_ACTION = (
    ("en", "nigger"),
    ("en", "kill yourself"),
    ("en", "i know where you live"),
    ("en", "shoot up the school"),
    ("en", "dont tell your parents"),
    ("en", "ill swat you"),
    ("en", "you retard"),
    ("cs", "buzerant"),
    ("cs", "cigoš"),
    # The pejorative acts; the ethnonym below does not, and must not drift back.
    ("cs", "zabij se"),
    ("cs", "vím kde bydlíš"),
    ("cs", "neříkej to rodičům"),
    ("cs", "ty negre"),
    # The other half of the mass-violence fix. Demoting the bare noun is only
    # right if the phrasings that name a speaker and a target still act, so they
    # are frozen here in the same breath.
    ("cs", "vystřílím školu"),
    ("da", "jeg laver et skoleskyderi"),
    ("de", "ich mache einen amoklauf"),
    ("hu", "lelövöm az iskolát"),
    ("pt", "vou explodir a escola"),
    ("sl", "razstrelil bom šolo"),
    ("sv", "jag gör en skolskjutning"),
    # The directed forms that keep the action while the bare token moved to
    # review tier.
    ("hu", "te cigány"),
    ("sl", "ti peder"),
    ("et", "pedekas"),
    ("et", "pederastid"),
    # The English slurs, in packs that had none of them.
    ("cs", "nigger"),
    ("el", "faggots"),
    ("pl", "faggot"),
    ("ru", "nigga"),
    ("sl", "nigger"),
    ("cs", "kys"),
    ("pl", "kys"),
    ("ru", "kys"),
    # German "kill yourself", which is the same three words as the threat above
    # with `ich` removed. The regex rule is what tells them apart.
    ("de", r"(?<!ich )\bbring dich (?:doch |endlich |einfach |selbst |lieber )?um\b"),
)

# Obfuscations that must still be caught, so that no benign corpus in this file
# can be satisfied by a matcher that has simply stopped matching.
FUZZY_MUST_STILL_CATCH = (
    ("en", "niggger", 3),
    ("en", "niiigger", 3),
    ("en", "faggggot", 3),
    ("cs", "buzeraaant", 3),
    ("cs", "buzzzerant", 3),
    ("cs", "cigooosh", 3),
)

# Explicit stem/fragment pairs. The first version treated any token in
# {ll, re, ve, m, s, t, d} as a contraction fragment, which asked cs.yml for
# `střelbave škole` and would ask a future English rule for `vitamins
# deficiency`. Naming the pairs removes the guesswork.
CONTRACTION_PAIRS = (
    ("i ll", "ill"),
    ("i m", "im"),
    ("i ve", "ive"),
    ("you re", "youre"),
    ("that s", "thats"),
    ("don t", "dont"),
)


def pack(language: str) -> RulePack:
    return RulePack.load(RULES_DIRECTORY / f"{language}.yml")


def rule_for(language: str, pattern: str):
    for rule in pack(language).rules:
        if pattern in rule.patterns:
            return rule
    return None


# ---------------------------------------------------------------------------
# The control: a dead matcher must not pass this file
# ---------------------------------------------------------------------------
@pytest.mark.parametrize(("language", "token", "severity"), FUZZY_MUST_STILL_CATCH)
def test_fuzzy_matching_is_alive(language: str, token: str, severity: int) -> None:
    """Every benign corpus below also passes if ``_match_fuzzy`` returns None for
    every token. This is what makes the benign corpora mean something."""
    verdict = pack(language).match(token)

    assert verdict.severity == severity, (token, verdict.matches)


# ---------------------------------------------------------------------------
# The confirmed collisions
# ---------------------------------------------------------------------------
@pytest.mark.parametrize("transcript", CONFIRMED_ENGLISH_COLLISIONS)
@pytest.mark.parametrize("language", LANGUAGES)
def test_confirmed_english_collisions_never_act(language: str, transcript: str) -> None:
    """No automatic action. Checked against both packs, because a mislabelled
    utterance is routed to whichever pack the detector picked."""
    verdict = pack(language).match(transcript)

    assert verdict.severity == 0, [(match.rule_id, match.matched_text) for match in verdict.matches]


@pytest.mark.parametrize("transcript", CONFIRMED_CZECH_COLLISIONS)
@pytest.mark.parametrize("language", LANGUAGES)
def test_confirmed_czech_collisions_never_act(language: str, transcript: str) -> None:
    verdict = pack(language).match(transcript)

    assert verdict.severity == 0, [(match.rule_id, match.matched_text) for match in verdict.matches]


# ---------------------------------------------------------------------------
# Game vocabulary must survive, silently
# ---------------------------------------------------------------------------
@pytest.mark.parametrize("transcript", BENIGN_MINECRAFT)
@pytest.mark.parametrize("language", LANGUAGES)
def test_english_game_speech_never_matches(language: str, transcript: str) -> None:
    verdict = pack(language).match(transcript)

    assert verdict.matches == (), [match.rule_id for match in verdict.matches]


@pytest.mark.parametrize("transcript", BENIGN_MINECRAFT_CZECH)
@pytest.mark.parametrize("language", LANGUAGES)
def test_czech_game_speech_never_matches(language: str, transcript: str) -> None:
    verdict = pack(language).match(transcript)

    assert verdict.matches == (), [match.rule_id for match in verdict.matches]


@pytest.mark.parametrize("transcript", GAMEPLAY_THREATS_ENGLISH)
def test_english_gameplay_threats_never_match(transcript: str) -> None:
    verdict = pack("en").match(transcript)

    assert verdict.matches == (), [match.rule_id for match in verdict.matches]


@pytest.mark.parametrize("transcript", GAMEPLAY_THREATS_CZECH)
def test_czech_gameplay_threats_never_match(transcript: str) -> None:
    verdict = pack("cs").match(transcript)

    assert verdict.matches == (), [match.rule_id for match in verdict.matches]


# ---------------------------------------------------------------------------
# Coverage, proved by an input rather than by metadata
# ---------------------------------------------------------------------------
@pytest.mark.parametrize("language", LANGUAGES)
def _fires_on_own_terms(loaded: RulePack, rule) -> bool:
    """Does this rule actually match something it itself lists?

    Regex rules are excluded because the loader already proves it for them: a
    regex rule must carry a ``probe`` that is verified to match after
    normalisation, and the probe is not kept on the parsed rule to replay here.
    """
    return any(
        any(match.rule_id == rule.rule_id for match in loaded.match(pattern).matches)
        for pattern in rule.patterns
    )


@pytest.mark.parametrize("language", LANGUAGES)
def test_every_rule_fires_on_its_own_terms(language: str) -> None:
    """A rule that cannot match anything is worse than no rule: it reads as
    coverage.

    This replaced a pair of tests that asked every pack to flag a corpus of
    English or Czech sentences, chosen by ``if language == "en" else``. That was
    fine while the packs were English and Czech. Once the directory held
    twenty-three languages it demanded that a Polish pack flag Czech utterances,
    which is unsatisfiable without putting Czech phrases in the Polish pack, and
    that is precisely the cross-language false positive these packs exist to
    avoid. Reachability is a property of a pack against its own vocabulary, so
    it is now asked that way. Whether a *realistic sentence* reaches a rule stays
    language-specific, in the must-flag tests below.
    """
    loaded = pack(language)

    dead = [
        rule.rule_id
        for rule in loaded.rules
        if rule.match_type != "regex" and not _fires_on_own_terms(loaded, rule)
    ]

    assert dead == [], f"{language}: rules that match none of their own terms: {dead}"


@pytest.mark.parametrize("language", LANGUAGES)
def test_every_declared_category_and_severity_is_reachable(language: str) -> None:
    """Declaring a category is free. Reaching it is the claim worth testing."""
    loaded = pack(language)

    declared_categories = {rule.category for rule in loaded.rules if not rule.context_required}
    declared_severities = {rule.severity for rule in loaded.rules if not rule.context_required}
    reached_categories: set[str] = set()
    reached_severities: set[int] = set()
    for rule in loaded.rules:
        if rule.context_required or rule.match_type == "regex":
            continue
        for pattern in rule.patterns:
            verdict = loaded.match(pattern)
            for match in verdict.matches:
                if match.rule_id == rule.rule_id and not match.context_required:
                    reached_categories.add(match.category)
                    reached_severities.add(match.severity)

    assert declared_categories <= reached_categories | {
        rule.category for rule in loaded.rules if rule.match_type == "regex"
    }, f"{language}: declared but unreachable categories"
    assert declared_severities <= reached_severities | {
        rule.severity for rule in loaded.rules if rule.match_type == "regex"
    }, f"{language}: declared but unreachable severities"


# ---------------------------------------------------------------------------
# The phrasings a player actually uses
# ---------------------------------------------------------------------------
@pytest.mark.parametrize(("transcript", "severity", "rule_id"), MUST_FLAG_ENGLISH)
def test_english_realistic_utterances_flag(transcript: str, severity: int, rule_id: str) -> None:
    verdict = pack("en").match(transcript)
    matched = {match.rule_id: match for match in verdict.matches}

    assert rule_id in matched, sorted(matched)
    assert not matched[rule_id].context_required, rule_id
    assert verdict.severity == severity, (verdict.severity, sorted(matched))


@pytest.mark.parametrize(("transcript", "severity", "rule_id"), MUST_FLAG_CZECH)
def test_czech_realistic_utterances_flag(transcript: str, severity: int, rule_id: str) -> None:
    verdict = pack("cs").match(transcript)
    matched = {match.rule_id: match for match in verdict.matches}

    assert rule_id in matched, sorted(matched)
    assert not matched[rule_id].context_required, rule_id
    assert verdict.severity == severity, (verdict.severity, sorted(matched))


# ---------------------------------------------------------------------------
# The sentences the audit reproduced, in the pack that answered them
# ---------------------------------------------------------------------------
# Every one of these produced an automatic action -- a one-hour mute in all but
# one case -- and every one of them is ordinary speech. They must now reach a
# rule (so staff still see them) and act on nobody.
MUST_ALERT_WITHOUT_ACTING = (
    ("en", "did you see that school shooting on the news", "en.threat.mass-violence-ambiguous"),
    ("en", "there was a school shooting in the news again", "en.threat.mass-violence-ambiguous"),
    ("cs", "ve zprávách byla střelba ve škole", "cs.threat.mass-violence-ambiguous"),
    ("sv", "det var en skolskjutning på nyheterna", "sv.threat.mass-violence-ambiguous"),
    # Portuguese for "I need more stone", answered by the Slovene pack, which
    # every server runs because `languages: [auto]` runs all of them and merges.
    ("sl", "preciso de mais pedra", "sl.hate.homophobic-ambiguous"),
    ("sl", "preciso de mais pedra para a base", "sl.hate.homophobic-ambiguous"),
    # Croatian, answered by the Hungarian pack, which acted on a word hr.yml and
    # sl.yml both deliberately hold at review tier.
    ("hu", "eno ga cigo opet", "hu.hate.roma"),
    # Wishing death, in a game whose whole loop is dying and respawning.
    ("en", "go and die already i need that loot", "en.harassment.death-wish-ambiguous"),
    ("en", "i hope you die in the lava", "en.harassment.death-wish-ambiguous"),
    ("cs", "chcipni uz ty zombie", "cs.harassment.death-wish-ambiguous"),
    ("el", "ψοφα ρε", "el.harassment.death-wish-ambiguous"),
    ("hu", "dogolj meg te zombi", "hu.harassment.death-wish-ambiguous"),
    ("ru", "сдохни уже", "ru.harassment.death-wish-ambiguous"),
    ("es", "ojala te mueras en la lava", "es.harassment.death-wish-ambiguous"),
    # "I'll kill you" in German. This matched nothing at all before.
    ("de", "ich bring dich um", "de.threat.violence-ambiguous"),
    ("de", "ich bringe dich um", "de.threat.violence-ambiguous"),
    ("et", "este un pederast", "et.hate.homophobic-ambiguous"),
)

# The disclosures. Not one of these reached any rule in any of the twenty-three
# packs, because every self-harm rule everywhere was second person. They must
# reach staff and must never mute: a moderator checking on a player who turns out
# to be fine is survivable, and the alternative is muting a child who has just
# said the most important thing they will say all week.
DISCLOSURE_MUST_ALERT = (
    ("en", "i want to kill myself"),
    ("en", "im gonna kill myself tonight"),
    ("en", "i'm going to kill myself"),
    ("en", "kms"),
    ("en", "i wanna kms"),
    ("en", "i want to unalive myself"),
    ("en", "i cut myself last night"),
    ("en", "i want to die"),
    ("en", "nobody would miss me"),
    ("en", "honestly i dont want to be here anymore"),
    ("cs", "chci se zabít"),
    ("cs", "uz nechci zit"),
    ("de", "ich will mich umbringen"),
    ("es", "quiero matarme"),
    ("fr", "je veux me tuer"),
    ("pl", "chce sie zabic"),
    ("pt", "quero morrer"),
    ("ru", "хочу умереть"),
)

# Recall, in the same breath: demoting the ambiguous form is only defensible if
# the unambiguous one still carries the action.
STILL_ACTS = (
    ("en", "im going to shoot up the school tomorrow", 3, "en.threat.mass-violence"),
    ("cs", "zítra vystřílím školu", 3, "cs.threat.mass-violence"),
    ("de", "bring dich um", 3, "de.harassment.self-harm-imperative"),
    ("de", "bring dich doch um", 3, "de.harassment.self-harm-imperative"),
    ("de", "geh dich umbringen", 3, "de.harassment.self-harm"),
    ("sl", "ti peder", 3, "sl.hate.slur-directed"),
    ("hu", "te cigány", 3, "hu.hate.roma-directed"),
    ("cs", "nigger", 3, "cs.hate.slur-english"),
    ("pl", "faggot", 3, "pl.hate.slur-english"),
    ("cs", "kys", 3, "cs.harassment.self-harm"),
)


@pytest.mark.parametrize(("language", "transcript", "rule_id"), MUST_ALERT_WITHOUT_ACTING)
def test_the_reproduced_false_positives_alert_and_act_on_nobody(
    language: str, transcript: str, rule_id: str
) -> None:
    verdict = pack(language).match(transcript)
    matched = {match.rule_id for match in verdict.matches}

    assert rule_id in matched, sorted(matched)
    assert verdict.severity == 0, [
        (match.rule_id, match.severity) for match in verdict.matches if not match.context_required
    ]


@pytest.mark.parametrize(("language", "transcript"), DISCLOSURE_MUST_ALERT)
def test_self_harm_disclosure_reaches_staff_and_mutes_nobody(
    language: str, transcript: str
) -> None:
    verdict = pack(language).match(transcript)
    matched = {match.rule_id: match for match in verdict.matches}
    rule_id = f"{language}.harassment.self-harm-disclosure"

    assert rule_id in matched, sorted(matched)
    assert matched[rule_id].context_required, rule_id
    assert verdict.severity == 0, [
        (match.rule_id, match.severity) for match in verdict.matches if not match.context_required
    ]


@pytest.mark.parametrize("language", LANGUAGES)
def test_every_pack_can_see_a_self_harm_disclosure_at_all(language: str) -> None:
    """The gap was total: twenty-three packs, twenty-three second-person rules,
    nothing anywhere for a player talking about themselves. `kms` is the one
    string every pack can carry, so it is the floor this asserts."""
    verdict = pack(language).match("kms")

    assert f"{language}.harassment.self-harm-disclosure" in {
        match.rule_id for match in verdict.matches
    }
    assert verdict.severity == 0


@pytest.mark.parametrize(("language", "transcript", "severity", "rule_id"), STILL_ACTS)
def test_the_unambiguous_phrasing_still_acts(
    language: str, transcript: str, severity: int, rule_id: str
) -> None:
    verdict = pack(language).match(transcript)
    matched = {match.rule_id: match for match in verdict.matches}

    assert rule_id in matched, sorted(matched)
    assert not matched[rule_id].context_required, rule_id
    assert verdict.severity == severity, (verdict.severity, sorted(matched))


def test_kys_stays_out_of_the_four_packs_that_collide_with_danish() -> None:
    """`kys` is the ordinary Danish word for a kiss, and da, de, nl and sv all
    say so in their headers. It was added to the thirteen packs where that
    argument does not apply and deliberately not to these four, because a German
    or Dutch server is exactly the one likely to have da.yml enabled beside it.

    The gap this does *not* close is worth naming: en.yml, es, fr, it, pt and ro
    have carried `kys` at severity 3 all along, and under `languages: [auto]`
    every pack answers every utterance, so a Danish player saying `giv mig et
    kys` is already muted for an hour by en.yml. No entry in any pack can fix
    that -- `allow` is per-pack and the match comes from a different one -- so it
    is written down here rather than left to a support ticket."""
    for language in ("da", "de", "nl", "sv"):
        listed = {pattern for rule in pack(language).rules for pattern in rule.patterns}
        assert "kys" not in listed, language

    assert pack("da").match("giv mig et kys").matches == ()
    assert pack("en").match("giv mig et kys").severity == 3


# ---------------------------------------------------------------------------
# The review tier, frozen at pattern level in both directions
# ---------------------------------------------------------------------------
@pytest.mark.parametrize(("language", "pattern"), MUST_BE_REVIEW_TIER)
def test_pattern_stays_in_the_review_tier(language: str, pattern: str) -> None:
    rule = rule_for(language, pattern)

    assert rule is not None, f"{pattern!r} is no longer listed in {language}.yml"
    assert rule.context_required, (
        f"{pattern!r} moved out of the review tier into {rule.rule_id} at severity "
        f"{rule.severity}; it has a reachable benign reading in this register"
    )


@pytest.mark.parametrize(("language", "pattern"), MUST_CARRY_AUTOMATIC_ACTION)
def test_pattern_still_carries_an_automatic_action(language: str, pattern: str) -> None:
    rule = rule_for(language, pattern)

    assert rule is not None, f"{pattern!r} is no longer listed in {language}.yml"
    assert not rule.context_required, f"{pattern!r} was demoted to review tier in {rule.rule_id}"


@pytest.mark.parametrize("language", LANGUAGES)
def test_a_review_tier_pattern_alone_never_reaches_an_automatic_action(language: str) -> None:
    """No skip. The first version guarded this with ``if all(match.context_required
    ...)``, which silently passed in exactly the case it claimed to reject -- a
    review pattern that also trips a mute-tier rule."""
    loaded = pack(language)

    for rule in loaded.rules:
        if not rule.context_required:
            continue
        for pattern in rule.patterns:
            verdict = loaded.match(pattern)
            acting = [match.rule_id for match in verdict.matches if not match.context_required]
            assert verdict.severity == 0, (rule.rule_id, pattern, acting)


# ---------------------------------------------------------------------------
# The allow layer
# ---------------------------------------------------------------------------
# Cross-pack tier disagreements that are known, deliberate, and a different thing
# from the collisions the test below exists to catch.
#
# The collisions are two unrelated words that happen to be the same string:
# `pedra` is a homophobic inflection in Slovene and a stone in Portuguese,
# `pederast` is a slur in Estonian and the clinical term in Romanian. Neither
# pack is wrong; the merge is. Those were fixed by moving the string to review
# tier in the pack that muted it.
#
# These are not that. Every entry below is the *same word in the same sense*,
# with two packs disagreeing about how offensive it is to their own speakers --
# `neger` is at review tier in Hungarian, Slovak and Estonian because the older
# generation used it neutrally, and at mute tier in Danish, German, Dutch and
# Swedish because it is the slur outright there. Harmonising them is a register
# question for a native speaker of each language, not something a matcher or a
# sweep can settle, and both answers are defensible.
#
# So they are frozen rather than fixed: the set cannot grow without somebody
# writing down why, and the day a native reviewer settles one of these, the entry
# comes out.
KNOWN_TIER_DISAGREEMENTS = frozenset(
    {
        # `neger` and its spellings. en reaches it through the *fuzzy* nword rule
        # rather than by listing it, which is worth knowing: `neger` is two
        # accepted drifts from `nigger`.
        ("et", "neeger", "en"),
        ("hu", "neger", "da"),
        ("hu", "neger", "de"),
        ("hu", "neger", "en"),
        ("hu", "neger", "nl"),
        ("hu", "neger", "sv"),
        ("hu", "néger", "en"),
        ("sk", "neger", "da"),
        ("sk", "neger", "de"),
        ("sk", "neger", "en"),
        ("sk", "neger", "nl"),
        ("sk", "neger", "sv"),
        # The Roma pejorative: hr holds it at review tier, cs and sk act on it.
        ("hr", "cigos", "cs"),
        ("hr", "cigoš", "cs"),
        ("hr", "cigos", "sk"),
        ("hr", "cigoš", "sk"),
    }
)


@pytest.mark.parametrize("language", LANGUAGES)
def test_no_review_tier_pattern_is_muted_by_a_different_pack(language: str) -> None:
    """The cross-language half of the test above, and the one that was missing.

    ``test_a_review_tier_pattern_alone_never_reaches_an_automatic_action`` asks
    each pack about its own review patterns. But ``languages: [auto]`` runs
    *every* pack against *every* utterance and merges the matches
    (``app._match_transcript``), so a word one pack deliberately holds at review
    tier is muted anyway if another pack lists it at mute tier. That is not a
    theoretical shape: it is `pedra`, correct Slovene and the Portuguese for
    stone; `cigo`, held at review tier by hr and sl and muted by hu; and
    `pederast`, held at review tier by ro and muted by et -- which nobody
    reported and this test found.

    A review-tier decision is a claim about a word, not about a file. If one pack
    can override another's, the decision means nothing.

    ``KNOWN_TIER_DISAGREEMENTS`` above carves out the cases where two packs mean
    the same word and disagree about its register, which is a different problem
    and not one this test can decide.
    """
    loaded = pack(language)
    review = {
        pattern
        for rule in loaded.rules
        if rule.context_required and rule.match_type != "regex"
        for pattern in rule.patterns
        if " " not in pattern
    }

    for other in LANGUAGES:
        if other == language:
            continue
        matcher = pack(other)
        for pattern in sorted(review):
            if (language, pattern, other) in KNOWN_TIER_DISAGREEMENTS:
                continue
            acting = [
                match.rule_id
                for match in matcher.match(pattern).matches
                if not match.context_required
            ]
            assert not acting, (
                f"{language}.yml holds {pattern!r} at review tier and {other}.yml mutes "
                f"for it ({acting}); under `languages: [auto]` both packs answer the "
                f"same utterance, so the review-tier decision does not hold"
            )


def test_every_known_tier_disagreement_is_still_real() -> None:
    """A carve-out that carves nothing out is a documented problem that no longer
    exists, reading as a live one. Same argument as
    ``test_every_allow_entry_actually_suppresses_something``."""
    for language, pattern, other in sorted(KNOWN_TIER_DISAGREEMENTS):
        rule = rule_for(language, pattern)
        assert rule is not None and rule.context_required, (
            f"{pattern!r} is no longer at review tier in {language}.yml; drop the carve-out"
        )
        acting = [
            match.rule_id
            for match in pack(other).match(pattern).matches
            if not match.context_required
        ]
        assert acting, (
            f"{other}.yml no longer acts on {pattern!r}; the disagreement is settled, "
            f"drop the carve-out"
        )


@pytest.mark.parametrize("language", LANGUAGES)
def test_no_allow_entry_shadows_a_listed_pattern(language: str) -> None:
    """The first version asserted that each allow term produces no match -- which
    is precisely what a shadowed rule does, so adding ``nigger`` to ``allow``
    made it pass. The real check compares the two lists."""
    loaded = pack(language)
    listed = {pattern for rule in loaded.rules for pattern in rule.patterns}

    for term in loaded.allow:
        assert term not in listed, (
            f"allow entry {term!r} is also a listed rule pattern, so that rule can "
            f"never fire on any input"
        )


@pytest.mark.parametrize("language", LANGUAGES)
def test_every_allow_entry_actually_suppresses_something(language: str) -> None:
    """An allow entry that suppresses nothing is dead weight hiding as a
    safeguard: it looks like a carve-out and documents a collision that may no
    longer exist. Each one has to earn its place."""
    loaded = pack(language)
    without_allow = RulePack(
        language=loaded.language,
        rules=loaded.rules,
        regex_timeout_seconds=loaded.regex_timeout_seconds,
        allow=(),
    )

    for term in loaded.allow:
        assert without_allow.match(term).matches != (), (
            f"allow entry {term!r} suppresses nothing; remove it"
        )
        assert loaded.match(term).matches == (), term


# ---------------------------------------------------------------------------
# Authoring traps, pinned so the next pack author gets a sentence not a puzzle
# ---------------------------------------------------------------------------
@pytest.mark.parametrize("language", LANGUAGES)
def test_fuzzy_patterns_are_long_enough_and_single_token(language: str) -> None:
    """``_match_fuzzy`` skips transcript tokens under four characters and compares
    one token at a time, so a short pattern or one containing a space is dead.
    The loader does not refuse either; this does."""
    for rule in pack(language).rules:
        if rule.match_type != "fuzzy":
            continue
        for pattern in rule.patterns:
            assert " " not in pattern, (
                f"{rule.rule_id}: fuzzy pattern {pattern!r} contains a space; "
                f"_match_fuzzy compares single tokens, so it can never fire"
            )
            assert len(pattern) >= 4, (
                f"{rule.rule_id}: fuzzy pattern {pattern!r} is under four characters; "
                f"_match_fuzzy skips shorter tokens before comparing"
            )


@pytest.mark.parametrize("language", LANGUAGES)
def test_fuzzy_patterns_have_no_adjacent_distinct_vowels(language: str) -> None:
    """Run structure is compared only when the run *counts* are equal. Two
    adjacent different vowels break that for one specific drift: swapping one
    into the other merges two runs. The pattern is not dead -- an exact token
    still matches -- but its tolerance is uneven in a way nothing else reports,
    so such patterns are listed as `exact` instead."""
    for rule in pack(language).rules:
        if rule.match_type != "fuzzy":
            continue
        for pattern in rule.patterns:
            for index in range(len(pattern) - 1):
                left, right = pattern[index], pattern[index + 1]
                assert not (_is_vowel(left) and _is_vowel(right) and left != right), (
                    f"{rule.rule_id}: fuzzy pattern {pattern!r} has adjacent distinct vowels "
                    f"{left!r}{right!r}; list it as `exact` instead"
                )


def test_contractions_ship_both_spellings() -> None:
    """``I'll`` normalises to ``i ll`` but ``Ill`` normalises to ``ill``, and the
    transcriber emits both. Checked in both directions from named pairs: the
    first version only walked spaced -> joined, so a rule listing only ``ill
    shoot you`` passed while ``I'll shoot you`` missed.

    English only. Czech writes no apostrophe contractions and the fragments are
    ordinary Czech prepositions, so the heuristic there asks for nonsense."""
    for rule in pack("en").rules:
        if rule.match_type == "regex":
            continue
        listed = set(rule.patterns)
        for pattern in rule.patterns:
            for spaced, joined in CONTRACTION_PAIRS:
                if pattern.startswith(f"{spaced} ") or f" {spaced} " in pattern:
                    twin = pattern.replace(f"{spaced} ", f"{joined} ", 1)
                elif pattern.startswith(f"{joined} ") or f" {joined} " in pattern:
                    twin = pattern.replace(f"{joined} ", f"{spaced} ", 1)
                else:
                    continue
                assert twin in listed, (
                    f"{rule.rule_id}: lists {pattern!r} but not {twin!r}; "
                    f"the transcriber emits both spellings of {spaced!r}/{joined!r}"
                )


@pytest.mark.parametrize("language", LANGUAGES)
def test_rule_ids_are_namespaced_to_their_pack(language: str) -> None:
    """The rule id is what a staff member reads in the Discord embed and what an
    owner quotes in a support ticket, so it has to say which pack it came from."""
    for rule in pack(language).rules:
        assert rule.rule_id.startswith(f"{language}."), rule.rule_id


@pytest.mark.parametrize("language", LANGUAGES)
def test_consonant_marked_terms_ship_a_de_accented_twin(language: str) -> None:
    """The matcher folds vowel marks but not consonant ones, and the shipped
    transcriber drops both. A term carrying ``š``, ``č``, ``ř``, ``ž``, ``ť``,
    ``ď`` or ``ň`` therefore needs the unmarked spelling listed too --
    ``cigoška`` had none, and ``ta cigoska`` matched nothing."""
    for rule in pack(language).rules:
        if rule.match_type == "regex":
            continue
        listed = set(rule.patterns)
        for pattern in rule.patterns:
            # The twin the packs actually ship is fully unmarked, not
            # consonant-only: the transcriber that drops `š` drops `ů` too, so
            # `připoj se na můj server` pairs with `pripoj se na muj server`.
            twin = "".join(
                character
                for character in unicodedata.normalize("NFKD", pattern)
                if not unicodedata.combining(character)
            )
            if twin == pattern:
                continue
            assert twin in listed, (
                f"{rule.rule_id}: lists {pattern!r} but not the de-accented {twin!r}; "
                f"the matcher does not fold consonant marks and the transcriber drops them"
            )
